'use strict';
const OPS={rho:{s:'ρ',n:'Ritme',c:'#38bdf8',v:.80},mu:{s:'μ',n:'Modulatie',c:'#a855f7',v:.70},iota:{s:'ι',n:'Interferentie',c:'#ef4444',v:.55},coh:{s:'C',n:'Coherentie',c:'#22c55e',v:.90},proj:{s:'Π',n:'Projectie',c:'#f3b52b',v:.75}};
const NODES={Pp:[0,3],Pm:[0,-3],F1:[-2,1],F2:[0,1],F3:[2,1],F4:[-2,-1],F5:[0,-1],F6:[2,-1],C:[0,0]};
const EDGES={rho:[['Pp','F2'],['F2','C'],['C','F5'],['F5','Pm']],mu:[['F1','F2'],['F2','F3'],['F4','F5'],['F5','F6']],iota:[['F1','C'],['F3','C'],['F4','C'],['F6','C']],coh:[['F1','F2'],['F2','F3'],['F3','C'],['C','F6'],['F6','F5'],['F5','F4'],['F4','C'],['C','F1']],proj:[['C','Pp'],['C','Pm'],['C','F1'],['C','F3'],['C','F4'],['C','F6']]};
let state={spread:.24,threshold:.58,res:128,fields:{},light:null,peaks:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function createUI(){
 const sliders=$('#sliders'),bars=$('#bars'),grid=$('#fieldGrid');
 Object.entries(OPS).forEach(([k,o])=>{
  sliders.insertAdjacentHTML('beforeend',`<div class="op-control"><div class="op-label"><span class="symbol" style="color:${o.c}">${o.s} <small>${o.n}</small></span><output id="${k}Out">${o.v.toFixed(2)}</output></div><input id="${k}" type="range" min="0" max="1" step="0.01" value="${o.v}"></div>`);
  bars.insertAdjacentHTML('beforeend',`<div class="bar"><div class="bar-head"><span style="color:${o.c}">${o.s} ${o.n}</span><b id="bar-${k}">0%</b></div><div class="track"><div class="fill" id="fill-${k}" style="color:${o.c};background:${o.c}"></div></div></div>`);
  grid.insertAdjacentHTML('beforeend',`<article class="card"><div class="title"><h2 style="color:${o.c}">${o.s} ${o.n}</h2><span>F${o.s}</span></div><canvas id="field-${k}" width="520" height="520"></canvas></article>`);
  $('#'+k).addEventListener('input',e=>{o.v=+e.target.value;$('#'+k+'Out').value=o.v.toFixed(2);render();});
 });
}
function normPoint([x,y]){return [(x+2.7)/5.4,(3.5-y)/7];}
function gaussLine(x,y,a,b,s){const vx=b[0]-a[0],vy=b[1]-a[1],wx=x-a[0],wy=y-a[1],t=Math.max(0,Math.min(1,(wx*vx+wy*vy)/(vx*vx+vy*vy||1))),dx=x-(a[0]+t*vx),dy=y-(a[1]+t*vy);return Math.exp(-(dx*dx+dy*dy)/(2*s*s));}
function gaussNode(x,y,p,s){const dx=x-p[0],dy=y-p[1];return Math.exp(-(dx*dx+dy*dy)/(2*s*s));}
function makeField(kind,n){const a=new Float32Array(n*n), edges=EDGES[kind]; for(let j=0;j<n;j++)for(let i=0;i<n;i++){const x=i/(n-1),y=j/(n-1);let v=0; edges.forEach(([u,w],idx)=>{const A=normPoint(NODES[u]),B=normPoint(NODES[w]);let q=gaussLine(x,y,A,B,state.spread*(kind==='coh'?1.15:.72));if(kind==='rho')q*=.65+.35*Math.cos(44*(y-.5))**2;if(kind==='mu')q*=.55+.45*(x+.25*Math.sin(10*y+idx));if(kind==='iota')q*=.6+.4*Math.abs(Math.sin(18*(x+y)));if(kind==='proj')q*=.55+Math.hypot(x-.5,y-.5);v+=q;}); if(kind==='coh')v+=1.35*gaussNode(x,y,normPoint(NODES.C),state.spread*.95); a[j*n+i]=v;} normalize(a);return a;}
function normalize(a){let lo=Infinity,hi=-Infinity;for(const v of a){if(v<lo)lo=v;if(v>hi)hi=v}const d=hi-lo||1;for(let i=0;i<a.length;i++)a[i]=(a[i]-lo)/d;}
function compute(){const n=state.res;Object.keys(OPS).forEach(k=>state.fields[k]=makeField(k,n));const out=new Float32Array(n*n);let wsum=0;Object.entries(OPS).forEach(([k,o])=>{wsum+=o.v;const f=state.fields[k];for(let i=0;i<out.length;i++)out[i]+=o.v*f[i];});if(wsum)for(let i=0;i<out.length;i++)out[i]/=wsum;normalize(out);state.light=out;state.peaks=findPeaks(out,n,state.threshold);}
function findPeaks(a,n,t){const p=[];for(let y=2;y<n-2;y++)for(let x=2;x<n-2;x++){const v=a[y*n+x];if(v<t)continue;let max=true;for(let j=-2;j<=2&&max;j++)for(let i=-2;i<=2;i++)if(i||j)if(a[(y+j)*n+x+i]>v){max=false;break}if(max)p.push({x:x/(n-1),y:y/(n-1),v});}return p.sort((a,b)=>b.v-a.v).slice(0,12);}
function palette(v){const stops=[[3,7,12],[8,38,66],[20,105,143],[34,197,94],[243,181,43],[255,245,195]],q=v*(stops.length-1),i=Math.min(stops.length-2,Math.floor(q)),t=q-i,a=stops[i],b=stops[i+1];return a.map((z,k)=>Math.round(z+(b[k]-z)*t));}
function drawField(canvas,a,n,emergent=false){const c=canvas.getContext('2d'),im=c.createImageData(n,n);for(let i=0;i<a.length;i++){let v=a[i];if(emergent){const bands=[.38,.48,state.threshold,.68,.78];v=bands.reduce((s,b)=>s+(a[i]>=b?1:0),0)/bands.length;}const rgb=palette(v);im.data.set([...rgb,255],i*4);}const off=document.createElement('canvas');off.width=n;off.height=n;off.getContext('2d').putImageData(im,0,0);c.imageSmoothingEnabled=true;c.drawImage(off,0,0,canvas.width,canvas.height);if(emergent){c.strokeStyle='#fff8';c.lineWidth=1;state.peaks.forEach(p=>{c.beginPath();c.arc(p.x*canvas.width,p.y*canvas.height,7+10*p.v,0,Math.PI*2);c.stroke();c.fillStyle='#fff';c.beginPath();c.arc(p.x*canvas.width,p.y*canvas.height,2.4,0,Math.PI*2);c.fill();});}}
function drawNetwork(){const cv=$('#network'),c=cv.getContext('2d'),W=cv.width,H=cv.height;c.clearRect(0,0,W,H);c.fillStyle='#03070c';c.fillRect(0,0,W,H);c.strokeStyle='#19354d';c.lineWidth=1;for(let i=1;i<10;i++){c.beginPath();c.moveTo(i*W/10,0);c.lineTo(i*W/10,H);c.stroke();c.beginPath();c.moveTo(0,i*H/10);c.lineTo(W,i*H/10);c.stroke();}Object.entries(OPS).forEach(([k,o])=>{c.strokeStyle=o.c;c.globalAlpha=.22+.68*o.v;c.lineWidth=2+4*o.v;EDGES[k].forEach(([u,w])=>{const A=normPoint(NODES[u]),B=normPoint(NODES[w]);c.beginPath();c.moveTo(A[0]*W,A[1]*H);c.lineTo(B[0]*W,B[1]*H);c.stroke();});});c.globalAlpha=1;Object.entries(NODES).forEach(([name,p])=>{const [x,y]=normPoint(p);const g=c.createRadialGradient(x*W,y*H,2,x*W,y*H,25);g.addColorStop(0,'#fff');g.addColorStop(.2,'#ffd66e');g.addColorStop(1,'#f3b52b00');c.fillStyle=g;c.beginPath();c.arc(x*W,y*H,25,0,Math.PI*2);c.fill();c.fillStyle='#fff6d1';c.font='22px Georgia';c.textAlign='center';c.fillText(name.replace('Pp','P+').replace('Pm','P-'),x*W,y*H-18);});}
function metrics(){const L=state.light,n=state.res;let mean=0,active=0,center=0;for(let y=0;y<n;y++)for(let x=0;x<n;x++){const v=L[y*n+x];mean+=v;if(v>=state.threshold)active++;const r=Math.hypot(x/(n-1)-.5,y/(n-1)-.5);if(r<.18)center+=v;}mean/=L.length;center/=Math.PI*.18*.18*n*n;const closure=Math.min(1,(OPS.coh.v*.55+OPS.rho.v*.2+OPS.mu.v*.1+OPS.proj.v*.15));const continuity=Math.min(1,center);const diamond=.5*closure+.5*continuity;const psi=diamond*mean;const q=Math.max(0,1-Math.abs(OPS.iota.v-OPS.coh.v)*.25);return {mean,active:active/L.length,closure,diamond,psi,q};}
function updateMetrics(){const m=metrics();Object.entries(OPS).forEach(([k,o])=>{$('#bar-'+k).textContent=Math.round(o.v*100)+'%';$('#fill-'+k).style.width=(o.v*100)+'%';});$('#metrics').innerHTML=`<dt>Gem. L_DG</dt><dd>${m.mean.toFixed(3)}</dd><dt>Actief veldoppervlak</dt><dd>${(m.active*100).toFixed(1)}%</dd><dt>ψ_L-kandidaten</dt><dd>${state.peaks.length}</dd><dt>Sluitingsdekking</dt><dd>${m.closure.toFixed(3)}</dd><dt>◇ prototype</dt><dd>${m.diamond.toFixed(3)}</dd><dt>Ψ prototype</dt><dd>${m.psi.toFixed(3)}</dd><dt>Q prototype</dt><dd>${m.q.toFixed(3)}</dd>`;}
function render(){state.spread=+$('#spread').value;state.threshold=+$('#threshold').value;state.res=+$('#resolution').value;$('#spreadOut').value=state.spread.toFixed(2);$('#thresholdOut').value=state.threshold.toFixed(2);compute();drawNetwork();drawField($('#light'),state.light,state.res);drawField($('#emergence'),state.light,state.res,true);Object.keys(OPS).forEach(k=>drawField($('#field-'+k),state.fields[k],state.res));updateMetrics();}
function reset(){Object.assign(OPS.rho,{v:.80});Object.assign(OPS.mu,{v:.70});Object.assign(OPS.iota,{v:.55});Object.assign(OPS.coh,{v:.90});Object.assign(OPS.proj,{v:.75});Object.entries(OPS).forEach(([k,o])=>{$('#'+k).value=o.v;$('#'+k+'Out').value=o.v.toFixed(2)});$('#spread').value=.24;$('#threshold').value=.58;render();}
function exportJSON(){const m=metrics(),data={app:'EC-DynaMech',version:'0.1',status:'computed_not_independently_validated',topology:'R9',operators:Object.fromEntries(Object.entries(OPS).map(([k,o])=>[k,o.v])),parameters:{spread:state.spread,threshold:state.threshold,resolution:state.res},derived:{...m,psiL_candidates:state.peaks},definitions:{L_DG:'genormaliseerde afgeleide organisatie-intensiteit; geen fysieke luminantie',missing_not_zero:true}};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='EC-DynaMech_v0.1_toestand.json';a.click();URL.revokeObjectURL(a.href);}
createUI();
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tabview').forEach(v=>v.hidden=v.id!==b.dataset.tab);if(b.dataset.tab==='fields')render();});
$('#spread').oninput=render;$('#threshold').oninput=render;$('#resolution').onchange=render;$('#reset').onclick=reset;$('#export').onclick=exportJSON;$('#randomize').onclick=()=>{Object.entries(OPS).forEach(([k,o])=>{o.v=.15+Math.random()*.8;$('#'+k).value=o.v;$('#'+k+'Out').value=o.v.toFixed(2)});render();};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
